### PR TITLE
Include CachedKernel in gpdt.h

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by karlnapf** [comment]
including a shogun file in an external lib?

**Comment by ghost** [comment]
I moved typedefs from Kernel.h to CachedKernel.h, and they're needed gdpt.h

**Comment by karlnapf** [comment]
cool great!
so we merge this when the cache refactor is merged?

**Comment by ghost** [comment]
There are a couple of SVM related examples left. I will port those to make sure that integration data remains the same. Then I need to write some unit-tests (not sure what they would be like yet).

**Comment by karlnapf** [comment]
* using cache and not using cache yields same result
* the cache is actually used

**Comment by ghost** [comment]
The first part I intend to test by passing the integration tests before merging (since I can't not use caching with SVMLight, and it's only used by it).
The cache must be used in all cases, SVMLight always wraps the kernel in cachedkernel.

edit: my bad, I can control cache size, but this would be more of testing the cache functions than the refactor.

**Pull request closed without merging**
